
spring:
  rabbitmq:
    #连接地址
    host: 127.0.0.1
    #端口号   
    port: 5672
    #账号 
    username: admin
    #密码  
    password: admin
    #虚拟主机名
    virtual-host: admin_lyt
    #开启消息确认机制 confirms
    publisher-confirms: true
    publisher-returns: true
         
  #数据库连接信息
  datasource: 
        name: rabbitmq_order
        url: jdbc:mysql://127.0.0.1:3306/rabbitmq_order?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=TRUE
        username: root
        password: root
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8080